Vagrant.configure("2") do |config|
config.vm.provider "vmware_fusion" do |v|
end

# Web Server VM configuration
  config.vm.define "slave" do |slave|
    slave.vm.box = "spox/ubuntu-arm" # Use your preferred base box
  end
end
